controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: 'App\Controller\DefaultController::index'



login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: POST


api_get_animals:
    path: /api/animals
    controller: App\Controller\AnimalController::getAnimals
    methods: [GET]

api_add_animal:
    path: /api/animals
    controller: App\Controller\AnimalController::addAnimal
    methods: [POST]

api_delete_animal:
    path: /api/animals/{name}
    controller: App\Controller\AnimalController::deleteAnimal
    methods: [DELETE]


# Route pour soumettre un nouvel avis
review_create:
    path: /api/review
    controller: App\Controller\AvisController::submitReview
    methods: [POST]

# Route pour obtenir un avis par son ID
review_get:
    path: /api/review/{id}
    controller: App\Controller\AvisController::getReview
    methods: [GET]

# Route pour mettre à jour un avis existant
review_update:
    path: /api/review/{id}
    controller: App\Controller\AvisController::updateReview
    methods: [PUT]

# Route pour supprimer un avis par son ID
review_delete:
    path: /api/review/{id}
    controller: App\Controller\AvisController::deleteReview
    methods: [DELETE]

# config/routes.yaml

# Route de contact
contact:
    path: /api/contact
    controller: App\Controller\ContactController::contact
    methods: [POST]

signup:
    path: /signup
    controller: App\Controller\SignupController::signup
    methods: ['GET', 'POST']
vet_form_get_all:
    path: /api/vet-form
    controller: App\Controller\VetFormController::getAllVetForms
    methods: ['GET']

vet_form_get:
    path: /api/vet-form/{id}
    controller: App\Controller\VetFormController::getVetForm
    methods: ['GET']

vet_form_create:
    path: /api/vet-form
    controller: App\Controller\VetFormController::createVetForm
    methods: ['POST']

vet_form_update:
    path: /api/vet-form/{id}
    controller: App\Controller\VetFormController::updateVetForm
    methods: ['PUT']

vet_form_delete:
    path: /api/vet-form/{id}
    controller: App\Controller\VetFormController::deleteVetForm
    methods: ['DELETE']

# Route pour se connecter
user_login:
    path: /api/login
    controller: App\Controller\UserController::login
    methods: [POST]

# Route pour créer un nouvel utilisateur
user_create:
    path: /api/users
    controller: App\Controller\UserController::createUser
    methods: [POST]

# Route pour obtenir un utilisateur par son ID
user_get:
    path: /api/users/{id}
    controller: App\Controller\UserController::getUser
    methods: [GET]

# Route pour mettre à jour un utilisateur existant
user_update:
    path: /api/users/{id}
    controller: App\Controller\UserController::updateUser
    methods: [PUT]

# Route pour supprimer un utilisateur par son ID
user_delete:
    path: /api/users/{id}
    controller: App\Controller\UserController::deleteUser
    methods: [DELETE]

# Route pour obtenir la liste des offres
nos_offres_list:
    path: /api/nos-offres
    controller: App\Controller\NosOffresController::index
    methods: [GET]

# Route pour créer une nouvelle offre
nos_offres_create:
    path: /api/nos-offres
    controller: App\Controller\NosOffresController::create
    methods: [POST]

# Route pour mettre à jour une offre existante
nos_offres_edit:
    path: /api/nos-offres/{id}
    controller: App\Controller\NosOffresController::edit
    methods: [PUT]

# Route pour supprimer une offre par son ID
nos_offres_delete:
    path: /api/nos-offres/{id}
    controller: App\Controller\NosOffresController::delete
    methods: [DELETE]

# Route pour sauvegarder une photo (ajouter ou mettre à jour une photo)
api_save_photo:
    path: /api/photos
    controller: App\Controller\PhotoController::savePhoto
    methods: [POST, PUT]

# Route pour supprimer une photo
api_delete_photo:
    path: /api/photos
    controller: App\Controller\PhotoController::deletePhoto
    methods: [DELETE]

# Route pour obtenir tous les habitats
api_get_habitats:
    path: /api/habitats
    controller: App\Controller\HabitatController::list
    methods: [GET]

# Route pour obtenir un habitat spécifique par ID
api_get_habitat:
    path: /api/habitats/{id}
    controller: App\Controller\HabitatController::show
    methods: [GET]

# Route pour créer un nouvel habitat
api_create_habitat:
    path: /api/habitats
    controller: App\Controller\HabitatController::create
    methods: [POST]

# Route pour mettre à jour un habitat existant par ID
api_update_habitat:
    path: /api/habitats/{id}
    controller: App\Controller\HabitatController::update
    methods: [PUT]

# Route pour supprimer un habitat par ID
api_delete_habitat:
    path: /api/habitats/{id}
    controller: App\Controller\HabitatController::delete
    methods: [DELETE]
