# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    database_dsn: 'psql:host=127.0.0.1;dbname=your_database_name'
    database_user: 'your_database_user'
    database_password: 'your_database_password'


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false  # Par défaut, les services sont privés, sauf indication contraire.

    # Enregistre toutes les classes dans src/ comme services, sauf exceptions
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'  # Optionnel, si vous avez un répertoire de tests

    # Configuration du service PDO
    PDO:
        class: PDO
        arguments:
            - '%database_dsn%'
            - '%database_user%'
            - '%database_password%'
        calls:
            - [setAttribute, [\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION]]

    App\Repository\AvisRepository:
        arguments:
            $pdo: '@PDO'

    # Assurez-vous que les contrôleurs sont inclus comme services et tagués correctement
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true  # Les contrôleurs doivent être publics pour être accessibles via les routes

    # Si nécessaire, vous pouvez définir manuellement des services spécifiques ici